service: rws-mpc-api # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.7
  stage: 'dev'
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ NotesTable, Arn ]

  environment:
    variable1: value1

functions:
  hello:
    handler: handler.hello

# you can add CloudFormation resource templates here
Resources:
  - ${file(resources/api-gateway-errors.yml)}
  - ${file(resources/dynamodb-tables.yml)}

custom:
  stage: ${opt:stage, self:provider.stage}
  tableName: ${self:custom.stage}-notes
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
