service: rws-mpc-api # NOTE: update this with your service name

custom:
  projectName: 'MPC'
  stage: ${opt:stage, self:provider.stage}
  notesTableName: ${self:custom.stage}-notes
  categoriesTableName: ${self:custom.stage}-categories
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}

provider:
  name: aws
  runtime: python3.7
  stage: 'dev'
  region: us-east-1
  environment:
    CATEGORY_TABLE_NAME: ${self:custom.categoriesTableName}
    NOTE_TABLE_NAME: ${self:custom.notesTableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ NotesTable, Arn ]
        - "Fn::GetAtt": [ CategoriesTable, Arn ]

functions:
  - ${file(src/notes/functions.yml)}
  - ${file(src/categories/functions.yml)}

resources:
  - ${file(resources/api-gateway-errors.yml)}
  - ${file(resources/dynamodb-tables.yml)}
  - ${file(resources/s3-bucket.yml)}
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
